"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestControlContinuations,
	#superclass : #PackageManifest,
	#category : #'Control-Continuations'
}

{ #category : #'code-critics' }
ManifestControlContinuations class >> ruleRBMethodSourceContainsLinefeedsRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'Control-Continuations')) #'2018-11-10T19:04:41.650473+01:00') )
]
